package com.gep;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @gep
//  @ File Name : AbsoluteFitness.java
//  @ Date : 2013/4/5
//  @ Author : @shenzhan
//
//




public class AbsoluteFitness extends FitnessFunction {
	public void GetFitness() {
	
	}
	

}
