package com.gep;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @gep
//  @ File Name : FitnessFunction.java
//  @ Date : 2013/4/5
//  @ Author : @shenzhan
//
//




public abstract class FitnessFunction {
	public abstract void GetFitness();
}
